development:
  adapter: mysql2
  encoding: utf8
  database: dawaat_development
  username: root
  password: lamborghini9
  host: 127.0.0.1
  port: 3306

staging:
  adapter: mysql2
  encoding: utf8
  database: dawaat_staging
  username: root
  password:
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: dawaat_test
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
